### ISSUE TITLE
Add default NAXSI rules for common software.

### ISSUE THREAD

**Issue by lewismarshall** [UKHomeOffice/docker-ngx-openresty#3]
E.g. for Drupal, add these rules:
https://github.com/nbs-system/naxsi-rules/blob/master/drupal.rules

**Comment by jon-shanks** [comment]
We should really have default naxsi_core.rules as well as those will just be specific for drupal but not generic in nature. so really we should have both in there maybe:

1) An env to include the default naxsi rules as a boolean
2) An env to pull from specific places for the default rules

**Comment by lewismarshall** [comment]
All done.
